### ISSUE TITLE
Switch URL and Subtitle

### ISSUE THREAD

**Issue by mkjo** [lucaseverett/toolbar-dial-firefox#11]
Great addon, exactly what I missed.

I'd love to switch the subtitle below the box and the text in the box. Is this possible?

**Comment by lucaseverett** [comment]
@mkjo The subtitle is the Name of the bookmark. If you edit the properties of the bookmark and update the name, the subtitle will be updated.

The text in the box is automatically generated based on the domain, and that can't be modified.

**Comment by mkjo** [comment]
Hello,
oh, sorry, my wording was wrong...
I wanted to ask if it is possible to swap the subtitle and the text in the box. Then it is possible to control the big text in the box with the bookmark name.
I have several urls (edit.whatever.com) which end up in a big "edit". I'd prefer that I can use the bookmark title instead of the URL, so I can use the bookmark name "My Blog".
If you tell me where I find the corrosponding parts in the source code, I can try to change this by myself.

**Comment by lucaseverett** [comment]
Thank you for the feedback. At this time it isn't possible to switch the subtitle and the text in the box.

**Comment by lucaseverett** [comment]
@mkjo I have a beta/web demo for the ability to switch the title and URL. Please feel free to take a look, and let me know if you have any thoughts or feedback. The demo version runs in the browser and has some hard-coded bookmarks for testing.

https://demo-beta.toolbardial.com/

**Comment by mkjo** [comment]
Good morning,
yes, the sample looks perfect.
Good work.

**Comment by lucaseverett** [comment]
I'm glad you like it! The update is now available for Firefox!

Closed by 7448c2d3269115f37a33c38c49abf072ac8c5dff.
