### ISSUE TITLE
Latest update reset extension preferences to defaults.

### ISSUE THREAD

**Issue by rmesbah** [lucaseverett/toolbar-dial-firefox#13]
Extension auto-updated while firefox was open and wiped all preferences back to their defaults. Not a major issue but should be tested for on future releases.

**Comment by lucaseverett** [comment]
Thank you for the note @rmesbah. The reset was on purpose, as I changed the way some of the preferences work. I also hoped that the reset would encourage people to revisit the Options page and be introduced to the new preferences. I shouldn't need to do any more resets in the future.
