### ISSUE TITLE
Empty Toolbar dial

### ISSUE THREAD

**Issue by gitbbnka** [lucaseverett/toolbar-dial-firefox#5]
When i add dial about:config in bookmarks then moz-extension://7ec56b0a-5986-43b1-bd98-22a533930486/dist/index.html is empty.
P.S.  The app is very cool, thanks.

**Comment by lucaseverett** [comment]
Thank you for letting me know about this issue!

I will fix this and submit the update to Mozilla soon.

**Comment by lucaseverett** [comment]
Hi @gitbbnka. This issue has been fixed in version 1.0.11.

**Comment by gitbbnka** [comment]
Hi @lucaseverett, thanks for the answer! Does not work. [https://imgur.com/qAEB4ap.png](url)

**Comment by lucaseverett** [comment]
Hi @gitbbnka. For security reasons, Firefox does not allow a webpage to link to about:config. The fix that I published yesterday fixed the issue you noticed where Toolbar Dial is empty.
